name: Reddit to Telegram Bot

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache last post file
        uses: actions/cache@v4
        with:
          path: last_post.txt
          key: reddit-last-post-${{ github.ref }}
          restore-keys: |
            reddit-last-post-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser requests deep-translator beautifulsoup4

      - name: Debug last_post
        run: |
          echo "------ FILE ------"
          cat last_post.txt || echo "file not found"
          echo "------------------"

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_IDS: ${{ secrets.CHAT_IDS }}
          SUBREDDIT: ${{ secrets.SUBREDDIT }}
        run: python bot.py

      - name: Commit last_post.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add last_post.txt
          git diff --cached --quiet || git commit -m "Update last post"
          git push
